export const HOME     = '/'
export const SIGN_UP  ='/signup'
export const REGISTER = '/register'
export const UPLOAD   = '/uploads'
export const USER   = '/auth'
export const DOCS   = '/docs'
// export const MASTERS = '/movies'